/**
 * Adversarial Security Rules Test Suite for MD ART STUDIO
 * Verifies that all "Dirty Dozen" payloads from security_spec.md return PERMISSION_DENIED.
 */

export interface SecurityTestCase {
  id: number;
  name: string;
  collectionPath: string;
  operation: 'get' | 'list' | 'create' | 'update' | 'delete';
  auth: {
    uid: string;
    email: string;
    email_verified: boolean;
  } | null;
  payload?: Record<string, unknown>;
  expectedResult: 'PERMISSION_DENIED';
}

export const DIRTY_DOZEN_TESTS: SecurityTestCase[] = [
  {
    id: 1,
    name: 'Self-Assigned Admin Role Escalation',
    collectionPath: '/users/attacker_1',
    operation: 'create',
    auth: { uid: 'attacker_1', email: 'attacker@example.com', email_verified: true },
    payload: {
      uid: 'attacker_1',
      displayName: 'Attacker',
      role: 'admin',
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 2,
    name: 'Shadow Field Injection on User Profile',
    collectionPath: '/users/user_1',
    operation: 'create',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    payload: {
      uid: 'user_1',
      displayName: 'User One',
      role: 'customer',
      isVerifiedGhostField: true,
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 3,
    name: 'Unverified Email Admin Spoof on Products',
    collectionPath: '/products/prod_1',
    operation: 'delete',
    auth: { uid: 'spoof_admin', email: 'meghanabesatty@gmail.com', email_verified: false },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 4,
    name: 'Cross-User PII Scrape on users_private',
    collectionPath: '/users_private/victim_uid',
    operation: 'get',
    auth: { uid: 'attacker_uid', email: 'attacker@example.com', email_verified: true },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 5,
    name: 'Identity Spoofing on Order Creation',
    collectionPath: '/orders/order_101',
    operation: 'create',
    auth: { uid: 'attacker_uid', email: 'attacker@example.com', email_verified: true },
    payload: {
      orderNumber: 'MD-101',
      userId: 'victim_uid',
      customerName: 'Attacker',
      customerEmail: 'attacker@example.com',
      customerPhone: '9876543210',
      shippingAddress: '123 Fake St',
      itemsSummary: '1x Painted Tee',
      subtotal: 259,
      discountAmount: 0,
      couponCode: '',
      shippingCost: 0,
      totalAmount: 259,
      paymentMethod: 'razorpay',
      paymentGatewayId: 'pay_123',
      paymentStatus: 'Paid',
      orderStatus: 'Payment Confirmed',
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 6,
    name: 'Timestamp Forgery / Backdating on Review Creation',
    collectionPath: '/reviews/rev_1',
    operation: 'create',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    payload: {
      productId: 'prod_1',
      productName: 'Botanical Tee',
      userId: 'user_1',
      authorName: 'User One',
      rating: 5,
      comment: 'Great art!',
      approved: true,
      createdAt: '2020-01-01T00:00:00Z',
      updatedAt: '2020-01-01T00:00:00Z',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 7,
    name: 'Immortal Field Mutation (createdAt change on User update)',
    collectionPath: '/users/user_1',
    operation: 'update',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    payload: {
      uid: 'user_1',
      displayName: 'New Name',
      role: 'customer',
      createdAt: 'MUTATED_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 8,
    name: 'Terminal State Unlocking on Delivered Order',
    collectionPath: '/orders/delivered_order_1',
    operation: 'update',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    payload: {
      orderStatus: 'Cancelled',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 9,
    name: 'Orphaned Subcollection Write on Order Items',
    collectionPath: '/orders/non_existent_order/items/item_1',
    operation: 'create',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    payload: {
      orderId: 'non_existent_order',
      userId: 'user_1',
      productId: 'non_existent_product',
      productName: 'Ghost Item',
      productImage: '/img.jpg',
      price: 100,
      quantity: 1,
      customText: '',
      colorPreference: '',
      specialInstructions: '',
      referenceImageData: '',
      createdAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 10,
    name: 'Resource Exhaustion / ID Poisoning on SavedAddress',
    collectionPath: `/addresses/${'a'.repeat(200)}`,
    operation: 'create',
    auth: { uid: 'user_1', email: 'user1@example.com', email_verified: true },
    payload: {
      userId: 'user_1',
      fullName: 'User',
      phone: '9876543210',
      houseFlat: '1',
      street: 'x'.repeat(5000),
      area: 'Area',
      city: 'City',
      state: 'State',
      pinCode: '500001',
      country: 'India',
      isDefault: true,
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 11,
    name: 'Array Type & Size Overflow on Products',
    collectionPath: '/products/prod_overflow',
    operation: 'create',
    auth: { uid: 'admin_1', email: 'meghanabesatty@gmail.com', email_verified: true },
    payload: {
      name: 'Overflow Product',
      slug: 'overflow-product',
      categoryId: 'cat_1',
      categoryName: 'Canvas Paintings',
      price: 199,
      compareAtPrice: 299,
      description: 'Test',
      materials: 'Canvas',
      size: '6x6',
      stock: 5,
      inStock: true,
      customizable: true,
      featured: false,
      bestSeller: false,
      images: [12345],
      keywords: 'art',
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 12,
    name: 'Unauthorized Query Scraping on Orders List',
    collectionPath: '/orders',
    operation: 'list',
    auth: { uid: 'attacker_uid', email: 'attacker@example.com', email_verified: true },
    expectedResult: 'PERMISSION_DENIED',
  },
];
